name: iOS workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Xcode
        run: sudo xcode-select -s /Applications/Xcode-15.0.0-Beta.6.app
      - name: Test
        run: make test
